name: YehezGun CI

on:
  pull_request:
    branches: [main]

jobs:
  next:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Biome Formatter
        run: pnpm format:ci

      - name: Run Biome Linter
        run: pnpm lint

      - name: Run Unit Test
        run: pnpm test:ci

      - name: Run TypeScript
        run: pnpm typescript:ci

      - name: Run unit tests in CI environment
        run: pnpm test:ci

      - name: Build the application
        run: pnpm build
        env:
          UMAMI_WEB_ID: ${{secrets.UMAMI_WEB_ID}}
          UMAMI_SRC: ${{secrets.UMAMI_SRC}}
          SANITY_DATASET: ${{secrets.SANITY_DATASET}}
          SANITY_PROJECTID: ${{secrets.SANITY_PROJECT_ID}}
